df1<-read.csv(file.choose())
df2<-read.csv("C:/Users/Aryaman kalia/Desktop/finaltableau/netflix_titles.csv")
df3<-rbind(df1,df2)
head(df3)
dim(df3)
dim(df2)
dim(df1)
#write.csv(df3,"C:/Users/Aryaman kalia/Desktop/finaltableau/final_titles.csv")
df4<-read.csv(file.choose())
sum(is.na(df4))
